#!/bin/bash
pkill -f node > /dev/null 2>&1
pkill -f cloudflared > /dev/null 2>&1
cd ~/minha-radio
echo "⚡ Ligando o servidor..."
node server.js > /dev/null 2>&1 &
sleep 3
echo "⚡ Gerando link..."
cloudflared tunnel --url http://localhost:3000
