github.com:
    users:
        speedeee:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: speedeee
