[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0 /data/data/com.termux/files/home)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\x16\0\0\0\xc5\0\0\x5q\0\0\x2\x8a\0\0\x3\x18\0\0\0\xe5\0\0\x5o\0\0\x2\x88\0\0\0\0\0\0\0\0\b\x88\0\0\x3\x18\0\0\0\xe5\0\0\x5o\0\0\x2\x88)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///storage/569C-190C/bluetooth/11.%20Sidoka%20-%20nos%20%C3%A9%20mais%20que%20bom%28MP3_160K%29.mp3, file:///data/data/com.termux/files/home/Music/xigncode/75bb217b701afb4964cf001cda959062.mp3
times=-1, 0
